name: 'Tagger'
description: 'Creating a new release using the labels from the Pull Request'
author: 'Denis Panfilov'
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client.
    required: false
    default: ${{ action.token }}
  pr-number:
    description: PR number
    required: false
    default: ${{ action.event.number }}
  default-tag:
    description: Default tag
    required: false
    default: v0.0.0
runs:
  using: docker
  image: Dockerfile
# runs:
#   using: 'node16'
#   main: 'dist/main/index.js'
#   pre: 'dist/setup/index.js'
branding:
  icon: 'tag'
  color: 'orange'
